config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'user/sign_up', to: 'users#new'
  get 'user/account', to: 'users#show'
  delete 'user/:id/destroy_by_admin', to: 'users#destroy_by_admin'
  resource :user do
    collection do
      get 'profile'
      patch 'profile', to: 'users#profile_update'
      get 'sign_in'
      post 'sign_in', to: 'users#session_create'
      delete 'logout'
      get 'all_users'
    end
  end
  resources :rooms do
    collection do
      get 'posts'
      get 'search'
    end
    member do
      delete 'destroy_by_admin'
    end
  end
  resources :reservations, only: [:index, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :self_introduction, length: { maximum: 255 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :profile, :profile_update, :all_users, :destroy_by_admin]
  before_action :admin_user, only: [:all_users, :destroy_by_admin]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録完了しました！"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "編集内容が保存されました！"
      redirect_to user_account_path
    else
      render 'edit'
    end
  end

  def destroy
    if !current_user.admin?
      current_user.destroy
      flash[:success] = "アカウントが削除されました"
      redirect_to root_path
    else
      flash[:danger] = "管理者は削除できません"
      redirect_to root_path
    end
  end

  def profile
    @user = current_user
  end

  def profile_update
    @user = current_user
    if @user.update(params.require(:user).permit(:self_introduction))
      flash[:success] = "編集内容が保存されました！"
      redirect_to profile_user_path
    else
      render 'profile'
    end
  end

  def sign_in
  end

  def session_create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user&.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_back_or root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'sign_in'
    end
  end

  def logout
    log_out if logged_in?
    redirect_to root_path
  end

  def all_users
    @users = User.paginate(page: params[:page])
  end

  def destroy_by_admin
    @user = User.find_by(id: params[:id])
    if !@user.admin?
      @user.destroy
      flash[:success] = "選択したユーザーを削除しました"
      redirect_to all_users_user_path
    else
      flash[:danger] = "管理者自身は削除できません"
      redirect_to all_users_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= user.name %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", "/user/#{user.id}/destroy_by_admin", method: :delete,
                                                                 data: { confirm: "本当に削除しますか?" } %>
  <% end %>
</li>

app/views/users/all_users.html.erb
<h2>全てのユーザー</h2>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/edit.html.erb
<% provide(:button_text, "編集を保存する") %>
<h2>アカウント編集</h2>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "shared/form" %>    
      <p><%= link_to "ホーム画面に戻る", root_path %></p>
      <p><%= link_to "自己紹介文を編集する", profile_user_path %></p>
      <div class="gravatar_edit">
        <%= gravatar_for @user, size:45 %>
        <a href="https://gravatar.com/emails" target="_blank">change</a>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:button_text, "アカウントを作成する") %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render "shared/form" %>    
        <p><%= link_to "ホーム画面に戻る", root_path %></p>
    </div>
</div>

app/views/users/profile.html.erb
<% provide(:button_text, "編集を保存する") %>
<h2>自己紹介編集</h2>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with model: @user, url: profile_user_path, local: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        
        <%= f.label :self_introduction, "自己紹介" %>
        <%= f.text_area :self_introduction, class: 'form-control' %>
        
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      <% end %>
      <p><%= link_to "ホーム画面に戻る", root_path %></p>
      <p><%= link_to "アカウント情報を編集する", edit_user_path %></p>
    </div>
</div>

app/views/users/show.html.erb
<h2>アカウント情報</h2>
<div class="table-container">
  <table>
    <tr>
      <th>名前</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>メール</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th>アイコン画像</th>
      <td><%= gravatar_for @user, size:45 %></td>
    </tr>
    <tr>
      <th>自己紹介文</th>
      <td><%= @user.self_introduction %></td>
    </tr>
  </table>
</div>
<p><%= link_to "アカウント情報を編集する", edit_user_path %></p>
<p><%= link_to "自己紹介文を編集する", profile_user_path %></p>

app/views/users/sign_in.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with url: sign_in_user_path, scope: :session, local: true do |f| %>
              
          <%= f.label :email, "メール" %>
          <%= f.text_field :email, class: 'form-control' %>
              
          <%= f.label :password, "パスワード" %>
          <%= f.password_field :password, class: 'form-control' %>
          
          <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span>永続的セッションを利用しますか？</span>
          <% end %>

          <%= f.submit "ログイン", class: "btn btn-primary" %>
      <% end %>
      <p><%= link_to "新しいアカウントを作成", user_sign_up_path %></p>
    </div>
</div>