config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'user/sign_up', to: 'users#new'
  get 'user/account', to: 'users#show'
  delete 'user/:id/destroy_by_admin', to: 'users#destroy_by_admin'
  resource :user do
    collection do
      get 'profile'
      patch 'profile', to: 'users#profile_update'
      get 'sign_in'
      post 'sign_in', to: 'users#session_create'
      delete 'logout'
      get 'all_users'
    end
  end
  resources :rooms do
    collection do
      get 'posts'
      get 'search'
    end
    member do
      delete 'destroy_by_admin'
    end
  end
  resources :reservations, only: [:index, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  default_scope -> { order(created_at: :desc) }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number_of_people, presence: true
  validates :user_id, presence: true
  validates :room_id, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :logged_in_user, only: [:index, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @reservations = current_user.reservations.paginate(page: params[:page])
  end

  def create
    @user = User.find_by(id: current_user.id)
    @room = Room.find_by(id: params[:reservation][:room_id])
    @reservation = current_user.reservations.build(reservation_params)
    if @reservation.save
      flash[:success] = "予約内容が登録されました！"
      redirect_to reservations_path
    else
      render 'rooms/show'
    end
  end

  def edit
    @reservation = Reservation.find_by(id: params[:id])
  end

  def update
    @reservation = Reservation.find_by(id: params[:id])
    if @reservation.update(reservation_params)
      flash[:success] = "編集内容が保存されました！"
      redirect_to reservations_path
    else
      render 'edit'
    end
  end

  def destroy
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.destroy
    flash[:success] = "予約が取り消されました"
    redirect_to reservations_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :number_of_people, :user_id, :room_id)
  end

  def correct_user
    @reservation = Reservation.find(params[:id])
    @user = User.find(@reservation.user_id)
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_reservation.html.erb
<% room = Room.find_by(id: reservation.room_id) %>
<% total_price = (reservation.end_date - reservation.start_date) / (60 * 60 * 24) * reservation.number_of_people * room.price %>
<tr id="reservation-<%= reservation.id %>">
    <td><%= link_to image_tag(room.display_image), room_path(room.id) %></td>
    <td><%= link_to room.name, room_path(room.id) %></td>
    <td><%= room.room_introduction %></td>
    <td>¥<%= total_price.to_i %></td>
    <td><%= reservation.start_date %></td>
    <td><%= reservation.end_date %></td>
    <td><%= reservation.created_at %></td>
    <td><%= link_to "変更", edit_reservation_path(reservation) %></td>
    <td><%= link_to "取り消し", reservation_path(reservation), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
</tr>

app/views/reservations/edit.html.erb
<%= provide :button_text, "予約内容を更新する" %>
<h2>予約内容の変更</h2>
<%= render "shared/reservation_form" %>    

app/views/reservations/index.html.erb
<h2>予約済みルーム一覧</h2>
<h3>登録物件数 (<%= @reservations.count %>)</h3>

<%= will_paginate @reservations %>

<table class="table" width="100%">
  <tr>
    <th width="15%">ルーム画像</th>
    <th width="10%">ルーム名</th>
    <th width="15%">ルーム紹介</th>
    <th width="10%">合計料金</th>
    <th width="10%">開始日</th>
    <th width="10%">終了日</th>
    <th width="10%">予約確定日時</th>
    <th width="10%">予約内容変更</th>
    <th width="10%">予約の取消</th>
  </tr>
  <% if @reservations.any? %>
    <ol class="reservations">
      <%= render @reservations %>
    </ol>
  <% end %>
</table>

<%= will_paginate @reservations %>