config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'user/sign_up', to: 'users#new'
  get 'user/account', to: 'users#show'
  delete 'user/:id/destroy_by_admin', to: 'users#destroy_by_admin'
  resource :user do
    collection do
      get 'profile'
      patch 'profile', to: 'users#profile_update'
      get 'sign_in'
      post 'sign_in', to: 'users#session_create'
      delete 'logout'
      get 'all_users'
    end
  end
  resources :rooms do
    collection do
      get 'posts'
      get 'search'
    end
    member do
      delete 'destroy_by_admin'
    end
  end
  resources :reservations, only: [:index, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :room_introduction, presence: true, length: { maximum: 255 }
  validates :price, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :image, presence: true,
                    content_type: {
                      in: %w(image/jpeg image/gif image/png),
                      message: "must be a valid image format",
                    },
                    size: {
                      less_than: 5.megabytes,
                      message: "should be less than 5MB",
                    }

  def display_image(height = 300, width = 300)
    image.variant(resize_to_limit: [height, width])
  end

  def self.search(search_word, column)
    where(["#{column} LIKE ?", "%#{search_word}%"])
  end

  # def self.search(search_words, column)
  # search_array = []
  # search_words.each do |search_word|
  # search_array.push("%#{search_word}%")
  # end
  # self.where(["#{column} LIKE ?", search_array])
  # end

  def self.minus_search(search_word, column)
    where(["#{column} NOT LIKE ?", "%#{search_word.delete_prefix('-')}%"])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :posts]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :admin_user, only: [:index, :destroy_by_admin]

  def index
    @rooms = Room.paginate(page: params[:page])
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    @room.image.attach(params[:room][:image])
    if @room.save
      flash[:success] = "部屋が登録されました！"
      redirect_to posts_rooms_path
    else
      render 'new'
    end
  end

  def show
    @room = Room.find_by(id: params[:id])
    @user = User.find_by(id: @room.user_id)
    @reservation = @room.reservations.build
  end

  def edit
    @room = Room.find_by(id: params[:id])
  end

  def update
    @room = Room.find_by(id: params[:id])
    if @room.update(room_params)
      flash[:success] = "編集内容が保存されました！"
      redirect_to posts_rooms_path
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find_by(id: params[:id])
    @room.destroy
    flash[:success] = "部屋情報が削除されました"
    redirect_to posts_rooms_path
  end

  def posts
    @user = current_user
    @rooms = @user.rooms.paginate(page: params[:page])
  end

  def search
    column = params[:column]
    keywords = params[:keyword].split(/[[:blank:]]+/).select(&:present?)
    negative_keywords, positive_keywords =
      keywords.partition { |keyword| keyword.start_with?("-") }

    @searched_rooms = Room.none

    positive_keywords.each do |keyword|
      @searched_rooms = @searched_rooms.or(Room.search(keyword, column))
    end

    negative_keywords.each do |keyword|
      @searched_rooms = @searched_rooms.minus_search(keyword, column)
    end

    @strict_searched_rooms = @searched_rooms

    positive_keywords.each do |keyword|
      @strict_searched_rooms.nil? ? break : @strict_searched_rooms = @strict_searched_rooms.search(keyword, column)
    end

    if !@strict_searched_rooms.nil?
      strict_searched_room_ids = []
      @strict_searched_rooms.each do |strict_searched_room|
        strict_searched_room_ids.push(strict_searched_room.id)
      end
      @searched_rooms = @searched_rooms.where.not(id: strict_searched_room_ids)
    end
  end

  def destroy_by_admin
    @room = Room.find_by(id: params[:id])
    @room.destroy
    flash[:success] = "部屋情報が削除されました"
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name, :room_introduction, :price, :address, :image)
  end

  def correct_user
    @room = Room.find(params[:id])
    @user = User.find(@room.user_id)
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<tr id="room-<%= room.id %>">
    <td><%= link_to image_tag(room.display_image), room_path(room.id) %></td>
    <td><%= link_to room.name, room_path(room.id) %></td>
    <td><%= room.room_introduction %></td>
    <td><%= room.price %></td>
    <td><%= room.created_at %></td>
    <% if !current_user.nil? && current_user.admin? %>
        <td><%= link_to "管理人による削除", destroy_by_admin_room_path(room.id), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
    <% elsif !current_user.nil? && current_user.id == room.user_id %>
        <td><%= link_to "削除", destroy_room_path(room.id), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
    <% end %>
</tr>

app/views/rooms/edit.html.erb
<% provide(:button_text, "部屋情報を更新する") %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render "shared/room_form" %>    
        <p><%= link_to "ホーム画面に戻る", root_path %></p>
    </div>
</div>

app/views/rooms/index.html.erb
<h2>全ユーザーの登録済みルーム一覧</h2>
<h3>登録物件数 (<%= @rooms.count %>)</h3>

<%= will_paginate @rooms %>

<table class="table" width="100%">
  <tr>
    <th width="35%">ルーム画像</th>
    <th width="10%">ルーム名</th>
    <th width="30%">ルーム紹介</th>
    <th width="10%">料金</th>
    <th width="10%">掲載日時</th>
    <th width="5%">削除</th>
  </tr>
  <% if @rooms.any? %>
    <ol class="rooms">
      <%= render @rooms %>
    </ol>
  <% end %>
</table>

<%= will_paginate @rooms %>

app/views/rooms/new.html.erb
<% provide(:button_text, "部屋を登録する") %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render "shared/room_form" %>    
        <p><%= link_to "ホーム画面に戻る", root_path %></p>
    </div>
</div>

app/views/rooms/posts.html.erb
<h2>登録済みルーム一覧</h2>
<h3>登録物件数 (<%= current_user.rooms.count %>)</h3>

<%= will_paginate @rooms %>

<table class="table" width="100%">
  <tr>
    <th width="35%">ルーム画像</th>
    <th width="10%">ルーム名</th>
    <th width="30%">ルーム紹介</th>
    <th width="10%">料金</th>
    <th width="10%">掲載日時</th>
    <th width="5%">削除</th>
  </tr>
  <% if current_user.rooms.any? %>
    <ol class="rooms">
      <%= render @rooms %>
    </ol>
  <% end %>
</table>

<%= will_paginate @rooms %>

app/views/rooms/search.html.erb
<h2>検索結果:
  <% if @searched_rooms.nil? && @strict_searched_rooms.nil? %>
    <%= "0件" %>
  <% elsif !@searched_rooms.nil? && !@strict_searched_rooms.nil? %>
    <%= "#{@searched_rooms.count.to_i + @strict_searched_rooms.count.to_i}件" %>
  <% elsif !@searched_rooms.nil? && @strict_searched_rooms.nil? %>
    <%= "#{@searched_rooms.count}件" %>
  <% elsif @searched_rooms.nil? && !@strict_searched_rooms.nil? %>
    <%= "#{@strict_searched_rooms.count}件" %>
  <% end %>
</h2>


<table class="table" width="100%">
  <tr>
    <th width="25%">ルーム画像</th>
    <th width="10%">ルーム名</th>
    <th width="40%">ルーム紹介</th>
    <th width="10%">料金</th>
    <th width="10%">掲載日時</th>
    <th width="5%">
      <%= "削除" if !current_user.nil? && (current_user.admin? || current_user.id == room.user_id) %>
    </th>
</tr>
  <div class="search-results-rooms">
    <% if !@strict_searched_rooms.nil? %>
      <div class="strict_searched_rooms">
        <%= render @strict_searched_rooms %>　<%# _room.html.erbが呼び出される %>
      </div>
    <% end %>
    <% if !@searched_rooms.nil? %>
      <div class="searched_rooms">
        <%= render @searched_rooms %>　<%# _room.html.erbが呼び出される %>
      </div>
    <% end %>
  </div>
</table>

app/views/rooms/show.html.erb
<% provide(:button_text, "予約する") %>
<h2>部屋詳細</h2>
<div class="row">
  <div class="col-md-8">
    <div class="room-image row">
      <p><%= image_tag(@room.display_image(600, 600)) %></p>
    </div>
    
    <div class="room-user row">
      <p><%= gravatar_for @user %></p>
      <p><%= @user.name %></p>
      <p><%= @user.self_introduction %></p>
    </div>
    
    <div class="room-introduction row">
      <p><%= @room.room_introduction %><p>
    </div>
  </div>
  <aside class="col-md-4">
    <div class="reservation-form row">
      <p><%= "¥#{@room.price}/日" %></p>
          <div class="col-md-6 col-md-offset-3">
              <p><%= render "shared/reservation_form" %></p>
              <p><%= link_to "ホーム画面に戻る", root_path %></p>
          </div>
    </div>
    
    <% if !current_user.nil? && current_user.id == @room.user_id %>
      <div class="edit-form row">
        <p><%= link_to "部屋情報を編集する", edit_room_path(@room.id) %></p> 
      </div>
      <div class="delete-room row">
        <p><%= link_to "登録した部屋を削除する", room_path(@room.id), method: :delete, data: { confirm: "本当に削除しますか?" } %></p>
      </div>
    <% end %>
    
  </aside>
</div>